blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/BankkRoll/skillforge#readme
    about: Check out the documentation before opening an issue
  - name: Discussions
    url: https://github.com/BankkRoll/skillforge/discussions
    about: Ask questions and discuss ideas
